import { Box } from '@mui/material';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { UserList } from '../components/userList';
import styles from '../styles/Home.module.css';

export default function Home() {
	const [users, setUsers] = useState([]);

	const queryData = async () => {
		const data = await fetch(
			'https://immense-shelf-01877.herokuapp.com/users'
		);
		const usersData = await data.json();
		setUsers(usersData);
	};

	useEffect(() => {
		queryData();
		console.log('desde el useEffect!!!');
	}, [users]);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Box sx={{ height: '90vh' }}>
				<h1 className={styles.title}>
					Welcome to <a>React Crud</a>
				</h1>
				<Box sx={{ mt: '50px' }}>
					<UserList userData={users} />
				</Box>
			</Box>

			{/* <footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer> */}
		</div>
	);
}
